---
openapi: 3.1.0
components:
  schemas:
    Greeting:
      description: A greeting message
      type: object
      properties:
        message:
          type: string
          description: The message to be displayed
    ImmutableList:
      type: array
    Response:
      type: object
      properties:
        greetings:
          description: A list of messages
          type: array
          items:
            type: array
            items:
              description: A greeting message
              type: object
              properties:
                message:
                  type: string
                  description: The message to be displayed
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
      summary: Hello
      tags:
      - Greeting Resource
info:
  title: quarkus-openapi-bug API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
